---
# tasks file for php

    - name: Update des packages originaux
      yum:
        name: '*'
        state: latest

    - name: Installation de Apache
      yum:
        name: httpd
        state: present

    - name: Start et enable du daemon Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Ouverture du port 443 (HTTPS)
      firewalld:
        service: https
        permanent: yes
        state: enabled

    - name: Ouverture du port 80 (HTTP)
      firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Installation du repo remi
      yum:
        name: "{{ remi_repo }}"
        state: present

    - name: Installation de PHP 7.4 et ses extensions
      yum:
        name:
          - php
          - php-bz2
          - php-mysql
          - php-curl
          - php-gd
          - php-intl
          - php-common
          - php-mbstring
          - php-xml
        enablerepo: remi-php74
        state: present

    - name: Restart d'Apache
      service:
        name: httpd
        state: restarted

